// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebClient;

#nullable disable

namespace WebClient.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("WebClient.Entities.BotUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalyticsResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("DotaBufURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamePosition")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InGameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LovelyHero")
                        .HasColumnType("TEXT");

                    b.Property<string>("MamaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PTSiki")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Tyanochka")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
